### ISSUE TITLE
Provide stream metadata via api

### ISSUE THREAD

**Issue by onny** [segler-alex/radiobrowser-api#27]
Hey,
it would be really nice if you could provide stream metadata via an api call. A lot of mp3 streams provide metadata of the radio station which includes the currently played track.

Best regards,
Jonas

**Comment by 0ttoman** [comment]
according to the faq the streams are currently checked about every two days to check if they are broken. While it could potentially also fetch the metadata, this would mean that things like 'currently playing' are always outdated.
This would be a great feature anyway because we could fetch the genres and add them to the database.
---
Lets say the average length of the tracks is 5 min, so the stream has to be checked about 12 times an hour to fetch at least most of the played tracks. 12 * 15000 (current stations) = 180000 (checks per hour) = 50 (checks per second)
I don't think this will be possible in the near future :/

**Comment by segler-alex** [comment]
i will close this, no stream will let me check that often. i already got kicked out on some channels when checking daily.
